A = int(input( "Digite o Valor de A : " ))
B = int(input( "Digite o Valor de B : " ))
C = int(input( "Digite o Valor de C : " ))
D = int(input( "Digite o Valor de D : " ))

print("A + B=", A + B)
print("A * B=", A * B)
print("A + C=", A + C)
print("A * C=", A * C)
print("A + D=", A + D)
print("A * D=", A * D)
print("B + C=", B + C)
print("B * C=", B * C)
print("B + D=", B + D)
print("B * D=", B * D)
print("C + D=", C + D)
print("C * D=", C * D)
